# This workflow will build the OpenDataHub Operator image and push it to the opendatahub image registry

name: Tag and Build

on:
  release:
    types:
      - created

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Set Go
      uses: actions/setup-go@v3
      with:
        go-version: v1.19

    - name: Login to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.QUAY_BOT_USER }}
        password: ${{ secrets.QUAY_BOT_PASSWORD }}
        registry: quay.io

    - name: Get Release Tag
      id: release-tag
      run: |
        release_tag=$(gh release view -R github.com/opendatahub-io/opendatahub-operator --json tagName | jq -r '.tagName')
        echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Image Build and Push
      run: |
        make build
        make image-build -e IMG=quay.io/opendatahub/opendatahub-operator:${{ env.RELEASE_TAG }}
        make image-push -e IMG=quay.io/opendatahub/opendatahub-operator:${{ env.RELEASE_TAG }}

